<a href="https://colab.research.google.com/github/soeun1030/pythorch_README/blob/main/01_tensor_quiz1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import numpy as np

## PyTorch Quiz 1 : Tensor 초기화

### 1. 빈 Tensor 생성하기
다음 조건에 맞는 Tensor를 생성하세요.
- 3x4 크기의 Tensor
- 값이 초기화되지 않은 상태

In [4]:
tensor = torch.empty(3, 4)
print(tensor)

tensor([[-9.3112e+11,  3.2932e-41,  1.5905e-42,  5.3756e-11],
        [-9.3113e+11,  3.2932e-41,  5.1848e-44,  1.3563e-19],
        [-9.3113e+11,  3.2932e-41,  1.5961e-42,  2.7909e+23]])


### 2. 0으로 채워진 Tensor 생성하기
다음과 같은 Tensor를 생성하세요.
- 2x5x3 크기의 Tensor
- 데이터 타입은 float64

In [5]:
a = torch.zeros(2, 5, 3, dtype=torch.float64)
print(a)

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]], dtype=torch.float64)


### 3. 1로 채워진 Tensor 생성하기
다음 조건에 맞는 Tensor를 생성하세요.
- 4x4 크기의 Tensor
- 데이터 타입은 int

In [6]:
a = torch.ones(4, 4, dtype=torch.int)
print(a)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)


### 4. 랜덤 값으로 채워진 Tensor 생성하기
다음 조건에 맞는 Tensor를 생성하세요.
- 3x3 크기의 Tensor
- 모든 값이 0과 1 사이의 랜덤 값

In [7]:
a = torch.rand(3, 3)
print(a)

tensor([[0.6598, 0.6484, 0.1577],
        [0.0413, 0.3627, 0.4302],
        [0.0432, 0.5253, 0.1674]])


### 5. 다차원 Tensor 생성하기
다음과 같은 다차원 Tensor를 생성하세요.
- 값이 다음과 같은 2x3의 2D 배열
    ```
    [[1, 2, 3],
     [4, 5, 6]]
    ```

In [18]:
nd_arr = np.array([[1, 2, 3], [4, 5, 6]])
tensor = torch.from_numpy(nd_arr)
new_nd = tensor.numpy()
print(new_nd)
print(tensor)

# 깔끔한 정답
a = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(a)

[[1 2 3]
 [4 5 6]]
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]])


### 6. Tensor의 값을 변경하기
1. 표준정규분포의 값을 랜덤으로 갖는 2x2 Tensor를 생성하세요.
2. 생성된 Tensor의 값을 모두 0으로 바꿔보세요.

In [19]:
a = torch.randn(2, 2)
b = a.zero_()
print(b)

# 정석 정답
c = torch.zeros_like(a)
print(c)

tensor([[0., 0.],
        [0., 0.]])
tensor([[0., 0.],
        [0., 0.]])
