<a href="https://colab.research.google.com/github/soeun1030/pythorch_README/blob/main/01_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip3 install torch

In [2]:
!pip3 install torchvision

In [10]:
import torch
torch.__version__

'2.5.1+cu121'

In [11]:
import numpy as np

#01. 텐서 초기화
### 초기화 : 텐서에 특정 값을 채워서 생성하는 것

## 1-1. 초기화되지 않은 Tensor
### 초기화되지 않은 텐서 : 특정한 값이 채워지지 않은 상태로 생성하는 것

In [12]:
tensor = torch.empty(4, 2)
print(tensor)

tensor([[1.5554e-43, 1.5975e-43],
        [1.3873e-43, 1.4574e-43],
        [1.4013e-44, 1.6255e-43],
        [1.5554e-43, 1.5975e-43]])


## 1-2. 상수로 초기화된 Tensor
### - torch.zeros()
### - torch.ones()

In [14]:
a = torch.ones(3, 4, dtype=torch.long)  #dytpe : 데이터 타입 지정
b = torch.zeros(2, 2)
print(a)
print(b)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])
tensor([[0., 0.],
        [0., 0.]])


## 1-3. 무작위로 초기화된 Tensor
### - torch.rand : 0 ~ 1 사이의 값으로 무작위로 초기화
### - torch.randn : 표준정규분포에서 무작위로 초기화

In [15]:
a = torch.rand(3, 3)
b = torch.randn(3, 3)
print(a, b)

tensor([[0.3698, 0.3287, 0.1660],
        [0.8994, 0.3264, 0.5337],
        [0.1850, 0.8077, 0.3904]]) tensor([[-0.4776, -0.5529,  0.1706],
        [-0.3713,  0.4774,  0.3191],
        [ 0.2059,  1.0412,  0.7804]])


## 1-4. 직접 입력한 값으로 초기화

In [16]:
a = torch.tensor([1,2.3])
a

tensor([1.0000, 2.3000])

## 1-5. Numpy 배열로부터 초기화

In [22]:
nd_arr = np.array([1,2,3])
a = torch.from_numpy(nd_arr)
a

# numpy array로 변환
b = torch.tensor([1, 2, 3, 4, 5])
new_nd = b.numpy()
new_nd[2] = 100
print(new_nd)
print(b)

[  1   2 100   4   5]
tensor([  1,   2, 100,   4,   5])


## 1-6. 특정 텐서와 같은 사이즈, 무작위로 값을 채움

In [20]:
a = torch.ones(3, 4, dtype=torch.long)
b = torch.rand_like(a, dtype=torch.float)
b

tensor([[0.3540, 0.4812, 0.5245, 0.1170],
        [0.9605, 0.6925, 0.9560, 0.8223],
        [0.5634, 0.4274, 0.5608, 0.2907]])