<a href="https://colab.research.google.com/github/soeun1030/pythorch_README/blob/main/01_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip3 install torch

In [ ]:
!pip3 install torchvision

In [3]:
import torch
torch.__version__

'2.5.1+cu121'

In [ ]:
import numpy as np

#01. 텐서 초기화
### 초기화 : 텐서에 특정 값을 채워서 생성하는 것

## 1-1. 초기화되지 않은 Tensor
### 초기화되지 않은 텐서 : 특정한 값이 채워지지 않은 상태로 생성하는 것

In [ ]:
tensor = torch.empty(4, 2)
print(tensor)

tensor([[1.5554e-43, 1.5975e-43],
        [1.3873e-43, 1.4574e-43],
        [1.4013e-44, 1.6255e-43],
        [1.5554e-43, 1.5975e-43]])


## 1-2. 상수로 초기화된 Tensor
### - torch.zeros()
### - torch.ones()

In [ ]:
a = torch.ones(3, 4, dtype=torch.long)  #dytpe : 데이터 타입 지정
b = torch.zeros(2, 2)
print(a)
print(b)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])
tensor([[0., 0.],
        [0., 0.]])


## 1-3. 무작위로 초기화된 Tensor
### - torch.rand : 0 ~ 1 사이의 값으로 무작위로 초기화
### - torch.randn : 표준정규분포에서 무작위로 초기화

In [ ]:
a = torch.rand(3, 3)
b = torch.randn(3, 3)
print(a, b)

tensor([[0.3698, 0.3287, 0.1660],
        [0.8994, 0.3264, 0.5337],
        [0.1850, 0.8077, 0.3904]]) tensor([[-0.4776, -0.5529,  0.1706],
        [-0.3713,  0.4774,  0.3191],
        [ 0.2059,  1.0412,  0.7804]])


## 1-4. 직접 입력한 값으로 초기화

In [ ]:
a = torch.tensor([1,2.3])
a

tensor([1.0000, 2.3000])

## 1-5. Numpy 배열로부터 초기화

In [ ]:
nd_arr = np.array([1,2,3])
a = torch.from_numpy(nd_arr)
a

# numpy array로 변환
b = torch.tensor([1, 2, 3, 4, 5])
new_nd = b.numpy()
new_nd[2] = 100
print(new_nd)
print(b)

[  1   2 100   4   5]
tensor([  1,   2, 100,   4,   5])


## 1-6. 특정 텐서와 같은 사이즈, 무작위로 값을 채움

In [ ]:
a = torch.ones(3, 4, dtype=torch.long)
b = torch.rand_like(a, dtype=torch.float)
b

tensor([[0.3540, 0.4812, 0.5245, 0.1170],
        [0.9605, 0.6925, 0.9560, 0.8223],
        [0.5634, 0.4274, 0.5608, 0.2907]])

## 1-7. 텐서의 속성

In [7]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

tensor = torch.rand(3, 4, dtype=torch.float64)
tensor = tensor.to(device)
print(tensor.size())  #사이즈
print(tensor.shape)  #사이즈
print(tensor.dtype)  #데이터 타입
print(tensor.device)  #디바이스

torch.Size([3, 4])
torch.Size([3, 4])
torch.float64
cuda:0


## 1-8. 특정 타입의 텐서 생성

In [11]:
tensor = torch.rand(3, 4, dtype=torch.float64)
print(tensor.dtype)

float_tensor = torch.FloatTensor([1,2,3])
print(float_tensor.dtype)

int_tensor = torch.IntTensor([1,2,3])
print(int_tensor.dtype)

torch.float64
torch.float32
torch.int32


## 1-9. 데이터타입 캐스팅

In [13]:
float_tensor = torch.FloatTensor([1,2,3])
print(float_tensor.int())

int_tensor = torch.IntTensor([1,2,3])
print(int_tensor.float())

tensor([1, 2, 3], dtype=torch.int32)
tensor([1., 2., 3.])


## 1-10. CUDA Tensor

In [18]:
tensor = torch.rand(3, 4, dtype=torch.float64)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
tensor = tensor.to(device)
tensor.device

device(type='cuda', index=0)

## 1-11. 다차원 Tensor 표현
### 1-11-1. 0D Tensor(Scalar)
#### 0D Tensor(Scalar) : 하나의 값을 담고 있는 텐서

In [21]:
t0 = torch.tensor(100)
print(t0.ndim)
print(t0.shape)
print(t0)

0
torch.Size([])
tensor(100)


### 1-11-2. 1D Tensor(Vector)
#### 1D Tensor(Vector) : 값들을 저장하고 있는 리스트와 유사한 텐서

In [22]:
t1 = torch.tensor([1,2,3])
print(t1.ndim)
print(t1.shape)
print(t1)

1
torch.Size([3])
tensor([1, 2, 3])


### 1-11-2. 2D Tensor(Matrix)
#### 2D Tensor(Matrix) : 행렬과 같은 모양으로 두개의 축이 존재

In [24]:
t2 = torch.tensor([[1,2,3], [4,5,6]])
print(t2.ndim)
print(t2.shape)
print(t2)

2
torch.Size([2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])


### 1-11-3. 3D Tensor(Cube)
#### 3D Tensor(Cube) : 큐브와 같은 형태로 세 개의 축이 존재

In [26]:
t3 = torch.tensor([[[1,2,3], [4,5,6], [7,8,9]],
                   [[1,2,3], [4,5,6], [7,8,9]],
                   [[1,2,3], [4,5,6], [7,8,9]]
                   ])
print(t3.ndim)
print(t3.shape)
print(t3)

3
torch.Size([3, 3, 3])
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


### 1-11-4. 4D Tensor
#### 4D Tensor : 4개의 축

In [29]:
t4 = torch.rand(2, 3, 4, 5)
t4

tensor([[[[0.5835, 0.0476, 0.7407, 0.7502, 0.5735],
          [0.9568, 0.7290, 0.0295, 0.0561, 0.6374],
          [0.9316, 0.5294, 0.9307, 0.2759, 0.1211],
          [0.0242, 0.0736, 0.7240, 0.1698, 0.3976]],

         [[0.5411, 0.5263, 0.0193, 0.1737, 0.8309],
          [0.3637, 0.8535, 0.5838, 0.4387, 0.2852],
          [0.7978, 0.1916, 0.5434, 0.4532, 0.5754],
          [0.1934, 0.1858, 0.7581, 0.4684, 0.4289]],

         [[0.5672, 0.7508, 0.9528, 0.0996, 0.7344],
          [0.1433, 0.6494, 0.5237, 0.9971, 0.6083],
          [0.5889, 0.1163, 0.7611, 0.6850, 0.8765],
          [0.3424, 0.4696, 0.0438, 0.4483, 0.1324]]],


        [[[0.3097, 0.2214, 0.3298, 0.0785, 0.3174],
          [0.3528, 0.3120, 0.3748, 0.5563, 0.7537],
          [0.3718, 0.3864, 0.5788, 0.5151, 0.8120],
          [0.2403, 0.6653, 0.9203, 0.6977, 0.7190]],

         [[0.6199, 0.6720, 0.4808, 0.6592, 0.1097],
          [0.7123, 0.7897, 0.7493, 0.1583, 0.5654],
          [0.8256, 0.0984, 0.2759, 0.6263, 0.2475],
  