<a href="https://colab.research.google.com/github/soeun1030/pythorch_README/blob/main/02_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 02. 텐서의 연산

In [1]:
import torch

## 2-1. 산술 연산

In [3]:
tensor = torch.rand(2,2)
print(tensor)

tensor = tensor * 2
print(tensor)

tensor = tensor + 1
print(tensor)

tensor([[0.1108, 0.0508],
        [0.8657, 0.6454]])
tensor([[0.2217, 0.1015],
        [1.7314, 1.2908]])
tensor([[1.2217, 1.1015],
        [2.7314, 2.2908]])


In [9]:
x = torch.rand(2,2)
y = torch.rand(2,2)
add = torch.add(x,y)
print(x, y)
print(x+y)
print(add)

# in-placd 바꿔치기 연산
y.add_(x)  #더하기한 결과를 y에 덮어씌운 것
print(y)

# 빼기
sub = torch.sub(x,y)
print(x-y)
print(sub)

# 곱하기
mul = torch.mul(x,y)
print(x*y)
print(mul)

# 나누기
div = torch.div(x,y)
print(x/y)
print(div)

tensor([[0.9896, 0.9342],
        [0.0531, 0.1183]]) tensor([[0.9892, 0.3742],
        [0.4032, 0.5288]])
tensor([[1.9788, 1.3084],
        [0.4563, 0.6471]])
tensor([[1.9788, 1.3084],
        [0.4563, 0.6471]])
tensor([[1.9788, 1.3084],
        [0.4563, 0.6471]])
tensor([[-0.9892, -0.3742],
        [-0.4032, -0.5288]])
tensor([[-0.9892, -0.3742],
        [-0.4032, -0.5288]])
tensor([[1.9583, 1.2224],
        [0.0242, 0.0765]])
tensor([[1.9583, 1.2224],
        [0.0242, 0.0765]])
tensor([[0.5001, 0.7140],
        [0.1164, 0.1828]])
tensor([[0.5001, 0.7140],
        [0.1164, 0.1828]])
