<a href="https://colab.research.google.com/github/soeun1030/pythorch_README/blob/main/02_operations_quiz2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

## PyTorch Quiz 2 : 연산

### 1. 덧셈과 뺄셈 연습
1. [2, 4, 6]으로 초기화된 1D Tensor를 생성하세요.
2. 각 요소에 5를 더한 Tensor를 출력하세요.
3. 각 요소에서 3을 뺀 Tensor를 출력하세요.


In [ ]:
a = torch.tensor([2,4,6])
b = torch.add(a, 5)  #b= a + 5
print(b)
add = torch.sub(a, 3)
print(add)

tensor([ 7,  9, 11])
tensor([-1,  1,  3])


### 2. Tensor 간의 연산
1. 3x3 크기의 Tensor 2개를 생성하세요.
2. 두 Tensor를 각각 더하고(+), 빼고(-), 곱하고(*), 나누세요(/).

In [ ]:
a = torch.rand(3,3)
b = torch.rand(3,3)

add = a + b
print(add)

sub = a - b
print(sub)

mul = a * b
print(mul)

div = a / b
print(div)

tensor([[1.5726, 0.4232, 1.0635],
        [1.3415, 0.7873, 1.3628],
        [0.9320, 1.1839, 1.2468]])
tensor([[ 0.4272,  0.1658,  0.3997],
        [-0.2281, -0.2041,  0.1166],
        [-0.9260, -0.5456,  0.3007]])
tensor([[0.5727, 0.0379, 0.2428],
        [0.4369, 0.1445, 0.4609],
        [0.0028, 0.2760, 0.3660]])
tensor([[1.7458, 2.2881, 2.2041],
        [0.7094, 0.5883, 1.1872],
        [0.0032, 0.3691, 1.6357]])


### 3. 행렬의 내적 연산
1. 2×3 크기의 Tensor A를 다음 값으로 생성하세요:
  - `[[1,2,3], [4,5,6]]`
2. 3×2 크기의 Tensor B를 다음 값으로 생성하세요:
  - `[[7,8],[9,10],[11,12]]`
3. 두 Tensor의 행렬 내적(행렬 곱) A×B를 계산하여 출력하세요.

In [ ]:
a = torch.tensor([[1,2,3], [4,5,6]])
b = torch.tensor([[7,8],[9,10],[11,12]])

mul = torch.matmul(a,b)
print(mul)

tensor([[ 58,  64],
        [139, 154]])


### 4. 행렬 연산과 값 제한
1. 이전 문제에서 계산된 행렬 R(결과 행렬 A×B)를 사용하세요
2. 행렬 R의 각 요소에 10을 더하세요.
3. R의 각 요소를 100보다 큰 값은 100으로, 나머지는 그대로 유지하도록 제한하세요.

In [ ]:
a = torch.tensor([[1,2,3], [4,5,6]])
b = torch.tensor([[7,8],[9,10],[11,12]])

mul = torch.matmul(a,b)

c = torch.add(mul, 10)  # c = mul + 10
print(c)

d = torch.clamp(c, min=100)
print(d)


tensor([[ 68,  74],
        [149, 164]])
tensor([[100, 100],
        [149, 164]])


### 5. 행렬의 열별 합계 계산
1. 5×5 크기의 Tensor M을 다음 값으로 생성하세요
    ```
    [[1, 2, 3, 4, 5],
     [6, 7, 8, 9, 10],
     [11, 12, 13, 14, 15],
     [16, 17, 18, 19, 20],
     [21, 22, 23, 24, 25]]
    ```

2. 행렬 M의 각 열의 합계를 계산하세요.

In [ ]:
a = torch.tensor([[1, 2, 3, 4, 5],
  [6, 7, 8, 9, 10],
  [11, 12, 13, 14, 15],
  [16, 17, 18, 19, 20],
  [21, 22, 23, 24, 25]])

b = torch.sum(a, dim=0)
print(b)

tensor([55, 60, 65, 70, 75])
