<a href="https://colab.research.google.com/github/soeun1030/pythorch_README/blob/main/03_manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 03. Tensor의 조작
## 3-1. 인덱싱, 슬라이싱
### : numpy처럼 활용

In [ ]:
import torch

In [ ]:
tensor = torch.tensor([[1,2], [3,4]])
print(tensor[0,1])  #2
print(tensor[0, :])  #[1,2]

a = torch.tensor([1,2,3,4,5])
print(a[-1])  #5
print(a[-2:])  #[4,5]

b = torch.tensor([[1,2,3], [4,5,6], [7,8,9]])
c = b[b > 5]
d = b[b % 2 == 0]
e = b[[0,1], [1,2]]
print(c)  #[6,7,8,9]
print(d)  #[2,4,6,8]
print(e)  #[2,6]

tensor(2)
tensor([1, 2])
tensor(5)
tensor([4, 5])
tensor([6, 7, 8, 9])
tensor([2, 4, 6, 8])
tensor([2, 6])
